services:
    postgres:
        image: postgres:15-alpine
        ports:
          - 5678:5678
        volumes:
            - ~/apps/postgres:/var/lib/postgresql/data
        environment:
            - POSTGRES_PASSWORD=S3cret
            - POSTGRES_USER=devfajar
            - POSTGRES_DB=task_management
